//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizzas
    {
        public System.Guid pizzaID { get; set; }
        public System.Guid customerID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Completed { get; set; }
    }
}
